### ISSUE TITLE
[Question] Extend/override properties of a parameter 

### ISSUE THREAD

**Issue by emauricio** [OAI/OpenAPI-Specification#2026]
Hello there,  I got a small question about the compoments[parameter]

Currently, im trying to make some parameters reusable and the basic seems pretty simple.
```
# 
openapi: 3.0.1
info:
  title: An include file to define common parameters
  version: 1.0.0
paths: 
    /test:
      get:
        ...
        parameters:
          - $ref: 'parameters.yml#/components/parameters/reusableParam'
        ...
components:
  parameters:
    reusableParam:
      in: query
      name: reusableParam
      description: filter something
      schema:
        type: number
        default: 30
```

Now my question is,  how can I avoid to duplicate the `reusableParam` if another path might need the same one but maybe with `required: true` or different `default: 50`

what would be the "correct" way to do it?

Thank you in advance.

**Comment by emauricio** [comment]
Any update about this?
It is quite funny that I end up in my own ticket some months later looking for the same. 😄

**Comment by bilak** [comment]
This would be very helpful. I'm also defining parameters which differ only with required attribute (true
|false).

**Comment by geoffreywiseman** [comment]
I have the exact same schema I need to use in three places, I just want to change the top-level description. The schema's the same, the description varies just slightly in ways that are subtly important. So instead of re-using it, I have to duplicate it.

**Comment by MikeRalphson** [comment]
@geoffreywiseman OAS (or whatever version the next release ends up as being) will support `$ref` with a sibling `description` property.

**Comment by geoffreywiseman** [comment]
OK, now I'm curious about why the next version might not be OAS. ;) Is there somewhere I go to read about that?

**Comment by MikeRalphson** [comment]
Sorry, there should have been a 3.1 in there, which got lost in editing!

**Comment by gfiehler** [comment]
I agree and also need this feature, but with the addition of wanting to override the example values on my parameters to be more relevant to each operation.  Or the ability to do some type of allOf on parameters where I can include an existing parameter definition and override one or more properties as you can with schemas.

**Comment by colin-p-hill** [comment]
Also running into a use for this. I've got parameters that are reused across multiple endpoints, but they're sometimes query parameters and sometimes path parameters, depending on whether they're identifying a single resource or filtering a collection of resources.

**Comment by osteel** [comment]
Yes, same need here. Also not the first time I end up on this thread 😄 

So much duplication going on in my OpenAPI definitions, at the moment.

**Comment by bansal6432** [comment]
I am also feeling the need for the same. 
Need to override name and required property for a path parameter.

**Comment by danielesegato** [comment]
I've another use-case for this

No reuse:
```
openapi: 3.0.0
components:
  schemas:
    TextContainer:
      type: object
      properties:
        format:
          title: Text Format
          description: Type of formatting of this text.
          type: string
          enum:
          - plain
          - html
          - markdown
          default: plain
        text:
          type: string
      required:
      - text

paths:
  /find:
    get:
      summary: FindTexts
      description: Find specific texts
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
        - name: only
          in: query
          required: false
          schema:
            description: Optionally filter a specific text type.
            type: string
            enum:
              - plain
              - html
              - markdown
              - any
            default: any
```

3 different features I'd like here, please note that:

1. the two usages have different description
2. the two usages have different default
3. the second usage has an additional property "on top" of the provided enum

The way I would like it to work:
```
openapi: 3.0.0
components:
  schemas:
    TextFormat:
      title: Text Format
      description: Type of formatting of this text.
      type: string
      enum:
        - plain
        - html
        - markdown
    TextContainer:
      type: object
      properties:
        format:
          $ref: '#/components/schemas/TextFormat'
          default: plain
        text:
          type: string
      required:
      - text

paths:
  /find:
    get:
      summary: FindTexts
      description: Find specific texts
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
        - name: only
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/TextFormat'
            description: Optionally filter a specific text type.
            enum:
              // some way to tell I want to add to the enum (a similar argument could be done for exclude)
              - $add: [any]
            default: any
```

**Comment by EmhyrVarEmreis** [comment]
Allowing to reuse referenced params with option to override "required" flag would be awsome

**Comment by Ramesh-X** [comment]
Is this going to be available in v3.1 ?

**Comment by MikeRalphson** [comment]
> Is this going to be available in v3.1 ?

3.1.0 is already out. You can override the `description` of a `parameterObject` in a `$ref`, but not (yet) the `required` field.

**Comment by mahnunchik** [comment]
Any news about overriding `required`?

**Comment by schmurfy** [comment]
Why not allow overriding everything instead of field by field ?
Here is what I would like to override:
- type: since in some case the param could be null and in others not (ex: `type: ["object", "null"]`)
- writeOnly & readOnly: same reason as above
- deprecated

it looks like for now `$ref` is just not doing the job for me unless I missed something

**Comment by tmtron** [comment]
We'd also like to override `example`/`examples`. We often have endpoints that return the same object, but the examples should be different

see also: https://github.com/nestjs/swagger/issues/1723

**Comment by axl8713** [comment]
As the Swagger Editor suggests, one could wrap the `$ref` into `allOff` to extend or override its properties:
```
parameters:
  - allOf:
      - $ref: '#/components/parameters/filters'
      - example: "overridden example"
  - $ref: '#/components/parameters/fields'
```
See https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#allof

**Comment by hkosova** [comment]
@axl8713 your example is unfortunately not a valid construct in OpenAPI.

> ```yaml
> parameters:
>   - allOf:
>       - $ref: '#/components/parameters/filters'
>       - example: "overridden example"
>   - $ref: '#/components/parameters/fields'
> ```

**Comment by axl8713** [comment]
> @axl8713 your example is unfortunately not a valid construct in OpenAPI.
> 
> > ```yaml
> > parameters:
> >   - allOf:
> >       - $ref: '#/components/parameters/filters'
> >       - example: "overridden example"
> >   - $ref: '#/components/parameters/fields'
> > ```

I've got misleaded by the Swagger Editor then, where it seems at least to be rendered correctly.

**Comment by billytetrud** [comment]
Having the same issues. Would very much want a consistent way to override properties. Others have mentioned examples of properties that basically need this functionality, but I don't see why the spec should pick and choose what properties are overridable.

**Comment by Midorina** [comment]
This, please.

**Comment by karenetheridge** [comment]
Anything below the `schema` keyword (which is about half of the requests in this thread) is not covered by the OpenAPI specification, but by JSON Schema. Please start a discussion at https://github.com/json-schema-org/community/discussions and we can help find a solution for you.

**Comment by billytetrud** [comment]
I wrote a pre-processing (or I guess a mid-processing) step for our own use that adds a command-like word `$merge`. It works like this:

```
$merge:
  - $ref: "some/path/to/a.yaml"
  - tags: # This overrides the tags property
      - "A tag"
    someOtherProp: 
      deeperProp: 'This also deeply overrides"
```

The `$merge` key should be a list, where each object in the list is merged in sequence (so later things override). This is really what I want in native openapi.

In the above example, the `tags` list will be overriden (not merged), and deep object properties will be merged as well. So if `a.yaml` has a `someOtherProp` object with a bunch of properties, `deeperProp` will be added alongside those properties.

```
const yaml = require('js-yaml');

const doc = yaml.load(bundle);
convertMerge(doc)
fs.writeFileSync(bundlePath, yaml.dump(doc))

// Executes $merge commands, mutates object.
// Returns either the mutated object, or a new object created from a merge.
function convertMerge(object) {
  for (const [key, value] of Object.entries(object)) {
    if (value instanceof Object) {
      try {
        object[key] = convertMerge(value)
      } catch(e) {
        if (e.code === 'convertMergeError') {
          updateConvertMergeError(e, key)
        }
        throw e
      }
    }
    if (key === '$merge') {
      if (Object.keys(object).length > 1) {
        throw convertMergeError("mergeNotAlone", key)
      }
      if (!(value instanceof Array)) {
        throw convertMergeError("mergeNotArray", key)
      }
      return convertMergeShallow(value)
    }
  }
  // else
  return object
}

function convertMergeShallow(mergeList) {
  const cur = {}
  mergeList.forEach(object => {
    Object.assign(cur, object)
  })
  return cur
}

function convertMergeError(message, key) {
  const e = new Error("mergeNotArray")
  e.code = 'convertMergeError'
  e.keylist = []
  e._message = message
  updateConvertMergeError(e, key)
  return e
}
function updateConvertMergeError(e, key) {
  e.keylist.unshift(key)
  e.message = e._message+' for key '+e.keylist.join('.')
}
```

**Comment by billytetrud** [comment]
@karenetheridge I and I believe others would also like ways to compose structures that are *not* under the `schema` keyword as well. Ideally this would have consistent composition semantics both within and outside of the `schema` keyword, like my $merge extension/hack does.

**Comment by kscheirer** [comment]
I am evaluating this as a possible use case for overlays, https://github.com/OAI/Overlay-Specification/discussions/9. 

Overlays more-or-less incorporate @billytetrud's suggestion in https://github.com/OAI/OpenAPI-Specification/issues/2026#issuecomment-1116418601, here is an attempt:
```json
{ 
  "overlay": "1.0.0",
  "info": {
    "title": "Merge example (Targeted)",
    "description": "Example from https://github.com/OAI/OpenAPI-Specification/issues/2026#issuecomment-1115404416",
    "version": "1.0.0"
  },
  "actions": [
    {
      "target": "$.tags",
      "description": "Remove tags entirely to override",
      "remove": true
    },
    {
      "target": "$.",
      "description": "new tag",
      "update": {
        "tags": [
          "A tag"
        ]
      }
    },
    {
      "target": "info.someOtherProp",
      "description": "deep object properties will be merged",
      "update": {
        "new_property": "A different property"
      }
    }
  ]
}
```

I think overlays would cover the use case from @danielesegato's comment as well, https://github.com/OAI/OpenAPI-Specification/issues/2026#issuecomment-801961448. I have seen this pattern used in contracts to reduce duplication, though not eliminate. I believe this is valid openapi: 

```contract.json
{
  "openapi": "3.0.0",
  "paths": {
    "/find": {
      "get": {
        "summary": "FindTexts",
        "description": "Find specific texts",
        "parameters": [
          {
            "name": "only",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/TextContainer/properties/format"
            }
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "TextContainer": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "format": {
            "type": "string",
            "enum": [
              "plain",
              "html",
              "markdown"
            ]
          }
        }
      }
    }
  }
}
```

then add overrides via overlay
```overlay.json
{ 
  "overlay": "1.0.0",
  "info": {
    "title": "Add options (Targeted)",
    "description": "Example from https://github.com/OAI/OpenAPI-Specification/issues/2026#issuecomment-801961448",
    "version": "1.0.0"
  },
  "actions": [
    {
      "target": "$.paths['get'].parameters[@.name =='only].schema",
      "description": "Add <any> option to request param",
      "update": {
        "enum": [
          "any"
        ]
      }
    },
    {
      "target": "$.paths['get'].parameters[@.name =='only]",
      "description": "Add any option to request param, add param description and default",
      "update": {
        "description": "Optionally filter a specific text type.",
        "default": "any",
        "schema": {
          "enum": [
            "any"
          ]
        }
      }
    },
    {
      "target": "$..parameters[@.in == 'query']..enum~",
      "description": "any query param with enum, not sure about target syntax",
      "update": {
          "enum": [
            "any"
          ]
        }
    }
  ]
}
```

**Comment by sorbonad** [comment]
Hi! Example in OAS3.1. I hope this helps:

```yaml
parameters:
        - in: query
          $ref: '../commons.yaml#/components/parameters/something'
          schema:
            default: myDefaultValue
```

**Comment by Kenpachi-zara** [comment]
> I wrote a pre-processing (or I guess a mid-processing) step for our own use that adds a command-like word `$merge`. It works like this:
> 
> ```
> $merge:
>   - $ref: "some/path/to/a.yaml"
>   - tags: # This overrides the tags property
>       - "A tag"
>     someOtherProp: 
>       deeperProp: 'This also deeply overrides"
> ```
> 
> The `$merge` key should be a list, where each object in the list is merged in sequence (so later things override). This is really what I want in native openapi.
> 
> In the above example, the `tags` list will be overriden (not merged), and deep object properties will be merged as well. So if `a.yaml` has a `someOtherProp` object with a bunch of properties, `deeperProp` will be added alongside those properties.
> 
> ```js
> const yaml = require('js-yaml');
> 
> const doc = yaml.load(bundle);
> convertMerge(doc)
> fs.writeFileSync(bundlePath, yaml.dump(doc))
> 
> // Executes $merge commands, mutates object.
> // Returns either the mutated object, or a new object created from a merge.
> function convertMerge(object) {
>   for (const [key, value] of Object.entries(object)) {
>     if (value instanceof Object) {
>       try {
>         object[key] = convertMerge(value)
>       } catch(e) {
>         if (e.code === 'convertMergeError') {
>           updateConvertMergeError(e, key)
>         }
>         throw e
>       }
>     }
>     if (key === '$merge') {
>       if (Object.keys(object).length > 1) {
>         throw convertMergeError("mergeNotAlone", key)
>       }
>       if (!(value instanceof Array)) {
>         throw convertMergeError("mergeNotArray", key)
>       }
>       return convertMergeShallow(value)
>     }
>   }
>   // else
>   return object
> }
> 
> function convertMergeShallow(mergeList) {
>   const cur = {}
>   mergeList.forEach(object => {
>     Object.assign(cur, object)
>   })
>   return cur
> }
> 
> function convertMergeError(message, key) {
>   const e = new Error("mergeNotArray")
>   e.code = 'convertMergeError'
>   e.keylist = []
>   e._message = message
>   updateConvertMergeError(e, key)
>   return e
> }
> function updateConvertMergeError(e, key) {
>   e.keylist.unshift(key)
>   e.message = e._message+' for key '+e.keylist.join('.')
> }
> ```
is it possible to do something similar as to adding a new 'message' field under components : schemas object for each propetry? then used in composition with 'pattern/min/max, etc../ fields

**Comment by ventsyv** [comment]
Late to the party, but using the same definition with different default values in different endpoints makes a lot of sense. As someone said just enable overriding for any property.

**Comment by pavelschon** [comment]
> BTW, is there any workaround we can use in the meantime?

Yes, use any macro language (e.g. python-jinja2 templates) to generate your OpenAPI specs.

**Comment by MikeRalphson** [comment]
> Would be a good idea to include YAML topics in the OpenAPI specification docs for general use cases.

@zalla2100 do you mean there should be examples of using YAML anchors and aliases etc in the specification itself, and/or in the `examples` directory?

@OAI/tsc I think we need to get some clarity on the intention of this paragraph in the spec.

> Tags MUST be limited to those allowed by the [JSON Schema ruleset](https://yaml.org/spec/1.2/spec.html#id2803231).
    Keys used in YAML maps MUST be limited to a scalar string, as defined by the [YAML Failsafe schema ruleset](https://yaml.org/spec/1.2/spec.html#id2802346).

YAML anchors and aliases (and merge keys in YAML 1.1) aren't tags or keys, they're node types AFAIK. Do we allow or disallow YAML anchors/aliases in OpenAPI documents?

**Comment by MikeRalphson** [comment]
@darrelmiller - counterpoint: does dereferencing a `$ref` cause loss?

**Comment by darrelmiller** [comment]
@MikeRalphson Maybe, maybe not. It depends on the implementation.  If you inline $refs and write out a new document without the $refs then absolutely I would say that is lossy.
Code generators rely heavily on component names that are pointed to by $refs. If you were to remove $refs by inlining, you couldn't generate the same client code.

**Comment by darrelmiller** [comment]
To qualify, I am not saying people should not use aliases to help them create OAS descriptions efficiently.  We full support folks who start with some other format and use tooling to create their OAS description.  If that tooling is a yaml parser that can dereference aliases, then all the power to you.
I am just saying it should not be EXPECTED that OAS compliant tooling will dereference aliases for you.

**Comment by MikeRalphson** [comment]
@darrelmiller which YAML parsers don't support aliases? 😁 Any OAS tool using a YAML parser is (almost certainly) going to support aliases whether we like it or not. (`oas-kit` checks the loaded object representation afterwards and warns by default on the use of aliases).

**Comment by darrelmiller** [comment]
@MikeRalphson  I don't know.  Are there YAML parsers that will enforce the JSON Schema ruleset, and if so will it still process aliases?

What if I rephrased and said that users should not expect OAS tooling to preserve aliases after parsing?

**Comment by MikeRalphson** [comment]
@darrelmiller I'll test with @eemeli'sv`yaml` implementation - it is very compliant with the YAML specification.

I'm about 75% minded the other way, in that we should allow alias fragments in `openapi+yaml`

**Comment by darrelmiller** [comment]
@MikeRalphson You're just a sucker for punishment ;-)

**Comment by ioggstream** [comment]
As long as the resulting document is valid OAS, limiting YAML syntax can be problematic and barely enforceable.

**Comment by MikeRalphson** [comment]
@darrelmiller I've tested with @eemeli's `yaml` implementation and it parses YAML aliases with the `core` and `failsafe` schemas, but not the `json` schema. So I think we're back to the question of what @OAI/tsc's intended ruling is on YAML aliases in OpenAPI documents, and whether we need language specifically about aliases, as they are neither tags nor mapping keys.

**Comment by eemeli** [comment]
> @darrelmiller I've tested with @eemeli's `yaml` implementation and it parses YAML aliases with the `core` and `failsafe` schemas, but not the `json` schema. [...]

Anchors and aliases are a YAML feature that's independent of the schema. The following works for me:

```js
import { parse } from 'yaml'

const src = `
"a": &a 42
"b": *a`

parse(src, { schema: 'core' }) // { a: 42, b: 42 }
parse(src, { schema: 'failsafe' }) // { a: '42', b: '42' }
parse(src, { schema: 'json' }) // { a: 42, b: 42 }
```

In your testing, you may have hit a stumbling block on string scalars needing to be quoted when using the `json` schema.

**Comment by MikeRalphson** [comment]
@darrelmiller Confirmed. You can use aliases in the JSON ruleset/schema if you quote your keys and values.

**Comment by fredericjaume-oc** [comment]
It would be great to be able to override example values. We have an in-house API testing framework that uses the examples to run some tests, and in some cases multiple endpoints sharing the same path parameter can't be tested with the same example value.

**Comment by zzafarr** [comment]
It's Jan 2024, still no solution ( > 4 years ) ?
It is totally makes sense that same type is/can be reused across in different schemas with different description, default values, is required, custom extensions  etc ..
Is this on the road map? 
What is the recommended workaround fir a time being?
Thank you

**Comment by handrews** [comment]
@zzafarr it is addressed by the [Moonwalk (OAS 4) proposal](https://github.com/OAI/moonwalk) - I'm pretty certain that the amount of change required can only be done in a major version update.  I have also filed #3508 to figure out how to clarify this sort of thing, as there are a lot of open issues in this repo that look abandoned but are actually being actively worked on in the Moonwalk repo.

**Comment by ChihweiLHBird** [comment]
Hi @handrews, thank you for the info! I just read the Moonwalk proposal, and I couldn't find a way to override the values in a `contentSchema` in a `request`. For example, `required` field in the `JSONSchema` (of `contentSchema`) can not be overridden. Do you think that was a part of this issue that's not resolved by the Moonwalk proposal? Or is there any way to do it but I missed?

**Comment by handrews** [comment]
@ChihweiLHBird the reason you couldn't find it is that it's not there, at least not yet, and it's not clear to us how to best address that use case.

With the scope of JSON Schema, well.. it's a [constraint system](https://modern-json-schema.com/json-schema-is-a-constraint-system) and requires a very different sort of organization for re-use than (for example) strongly typed OO languages like Java.

In the larger scope of OpenAPI, the [proposed Overlay Specification](https://github.com/OAI/Overlay-Specification) is one idea for doing such edits at a higher level, which would target 3.x.

For Moonwalk, we just don't know how it's all going to fit together yet.  Is JSON Schema even the right technology for all of this?  Should we use _more_ JSON Schema?  _Less_ JSON Schema?  Make it an option to replace it with something else?  All of this is being debated in-depth, and it's not clear where we will land yet.  The mismatch between JSON Schema as a constraint system and the needs of code generators is one of the most difficult topics we're working through.

**Comment by 9ao9ai9ar** [comment]
Can't this be done using `$dynamicAnchor`/`$dynamicRef`? [How do I override example for specific properties in components in OpenAPI?](https://stackoverflow.com/questions/68156028/how-do-i-override-example-for-specific-properties-in-components-in-openapi). Though even in 2024, I've yet to find tools that support these constructs... and you're planning to ship out OpenAPI 4 by the end of this year? Good luck with that. But please make sure to follow semantic versioning from this point onwards and write better documentation making it clear what features/vocabularies belong to what specifications and versions (e.g. JSON Schema 2020-12, YAML 1.2, etc.). It's very confusing for beginners when they first encounter "anchors" (JSON Schema anchors or YAML anchors?), or read articles describing OpenAPI as a "superset" of JSON Schema, but didn't actually support using `$id` and `$schema` in the OpenAPI documents.

**Comment by handrews** [comment]
@9ao9ai9ar as you can see in #3528 and #3529, we do intend to stick with semantic versioning.  3.1 was a very complex situation with no good option for compatibility, but it was also for a very specific reason which is not going to be a problem in the future.

3.0.4 and 3.1.1 should be out within a couple of months, and there will be a 3.2 (strictly compatible with 3.1, and with a small amount of enhancements that should make it fairly quick to implement) before there will be a 4.0.  We are looking at trying out 4.0 ideas in the 3.x series, so it's possible that shipping "Moonwalk" in 2024 will actually look like shipping incremental 3.x releases containing Moonwalk ideas rather than shipping a full 4.0 within the next few months.  It's very up in the air as of this week.

Some things in 3.0.4 and 3.1.1 are specifically about clarifying requirements that come from other specificaitons on which the OAS depends.

BTW, `$id` and `$schema` are supported in 3.1 OpenAPI documents.  If a tool does not support them, you should lobby the tooling vendor.

**Comment by handrews** [comment]
@9ao9ai9ar I forgot to answer your initial question - yes, at least some use cases can be handled by `$dynamicRef` and `$dynamicAnchor`.  In 3.1.1, we've added a section on how this construct can be used for generic types.  It's our hope that calling out a clear use case will motivate more tooling vendors to support it, especially because support for generic types has been requeseted many times (there were at least 5 open issues for it that I closed with 3.1.1).

**Comment by 9ao9ai9ar** [comment]
@handrews Looking forward to the 3.0.4 and 3.1.1 publications! I like the idea of doing incremental releases; even though OpenAPI still feels lacking in some areas, I think what we currently have in 3.1, if fully supported by available tools and documented clearly, is powerful enough to meet most requirements.

About `$id` and `$schema`, thank you for confirming that they are supported in OpenAPI 3.1, but it'll take some time for outdated information to decay into oblivion :). I only meantioned them because they appear in most examples using `$dynamicRef`/`$dynamicAnchor`, and I think no one has explained the background necessary for understanding these features better than Juan Cruz Viotti's [blog post](https://json-schema.org/blog/posts/understanding-lexical-dynamic-scopes).

I also have a need for generic types for a personal project I'm working on right now. Sadly, the tool I use is awesome in every way except not supporting `$dynamicRef`/`$dynamicAnchor` and YAML merge keys, the only two methods I know that should be able to achieve my goal. Fortunately, it's not really a blocker, so my situation is better than [this guy](https://github.com/OpenAPITools/openapi-generator/issues/9083#issuecomment-1163341420).

**Comment by guizoxxv** [comment]
I believe you could do:

```yml
openapi: 3.0.1
info:
  title: An include file to define common parameters
  version: 1.0.0
paths: 
    /test:
      get:
        parameters:
          - $ref: 'reusableParam.yaml'
        responses:
          200:
            description: OK
    /test-2:
      get:
        parameters:
          - name: reusableParam
            allOf:
              - $ref: 'reusableParam.yaml'
              - required: true
              - schema:
                type: number
                default: 50
        responses:
          200:
            description: OK
```

And in another file `reusableParam.yaml`:

```yml
name: reusableParam
in: query
description: filter something
schema:
  type: number
  default: 30
``

**Comment by handrews** [comment]
@guizoxxv `allOf` is a JSON Schema keyword and only usable inside of a Schema Object

**Comment by guizoxxv** [comment]
> @guizoxxv `allOf` is a JSON Schema keyword and only usable inside of a Schema Object

It seems to work when I run `npm run dev` on a local file in `swagger-ui`, but indeed it does not work when I try it in https://editor.swagger.io/.

**Comment by handrews** [comment]
This is as fixed as it's getting in 3.2, but see OAI/sig-moonwalk#20 and other discussions in OAI/sig-moonwalk for discussions of possible major version improvements in the future.
