### ISSUE TITLE
Schema Object / Items Object

### ISSUE THREAD

**Issue by pkriens** [OAI/OpenAPI-Specification#751]
I am a bit confused about the items in the Schema Object and Items Object. Unfortunately, the Schema Object is not layed out and must be inferred from a JSON Schema Draft specification.

In JSON Schema `items` is an array and it also needs `additionalItems`. However, in Items Object items is a singleton.

I am trying to map this to a type safe language with inheritance. It seems SchemaObject extends Items Object however, this clashes and is a huge pita therefore.

Is this difference in cardinality intentional?

**Comment by ePaul** [comment]
I think the fact that in JSON schema `items` can also be an array of schemas (meaning that the elements of the matched array have to match the schemas in turn) was not really meant to be supported by Swagger's schema object, but this was forgotten to be clarified in the specification. In the `Items object`, which is a slimmed down version thereof for query/path/form/header parameters and response headers, it was done as intended.

(This is just my impression, I was not there when the spec was written.)

For the next version (3.0, currently in progress), this is already fixed by having all parameters use a schema, and #741 is trying to get some more compatibility with JSON schema in it.

**Comment by pkriens** [comment]
Any idea when 3.0 will hit the streets? Are there already tools for it? I am having a greenfield situation and 3.0 looks a lot cleaner from a type perspective from what you're saying.

**Comment by webron** [comment]
The Items Object has been removed in 3.0. `items` definition has been clarified, and `additionalItems` is still not supported by the spec.

We're pushing out an implementer draft next week, tooling will follow.
